Add TLSH, Checksum column at report
fosslight/fosslight_android_scanner pull request #10
Opened 2024-03-20 04:48 UTC by bjk7119

## Description

- Add TLSH, Checksum column at report
    -  Hide these columns by default

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation update
- [ ] Refactoring, Maintenance
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

2024-03-20 07:04 UTC, soimkim requested changes

2024-03-20 07:04 UTC, soimkim commented on src/fosslight_android/_write_excel.py
> +    header_row.expend(hidden_header)
@bjk7119 , extend 아닌가요?

2024-03-20 07:04 UTC, soimkim commented on src/fosslight_android/_write_excel.py
> +        if hidden_header:
@bjk7119 , hidden_header는 최상단에 전역으로 정의해놔서 항상 True아닌가요?

2024-03-21 23:46 UTC, bjk7119 commented on src/fosslight_android/_write_excel.py
> +        if hidden_header:
맞습니다. 이것 때문에 고민했는데
어짜피 Default로 숨김 처리할 것이라면 if문을 삭제하겠습니다

2024-03-21 23:47 UTC, bjk7119 commented on src/fosslight_android/_write_excel.py
> +    header_row.expend(hidden_header)
OMG...

2024-03-22 00:03 UTC, soimkim commented on src/fosslight_android/_write_excel.py
> +hidden_header = ['TLSH', 'Checksum']
constant 변수는 다 대문자로 표기해주세요.
ex. hidden_header -> HIDDEN_HEADER

2024-03-22 00:38 UTC, soimkim commented on src/fosslight_android/_write_excel.py
> +    header_row.extend(hidden_header)
@bjk7119 , 요기도 고치셔야 합니다.

2024-03-22 00:39 UTC, soimkim commented on src/fosslight_android/_write_excel.py
>                    'License Text', 'Exclude', 'Comment', 'Need Check']
여기 header_row에 tlsh, checksum 용 column name 추가 안 되었습니다.

2024-03-27 00:44 UTC, soimkim commented on src/fosslight_android/_write_excel.py
> +    header_row.extend(HIDDEN_HEADER)
이것보다 header_row에 같이 명시하는게 더 명확해보여요~

2024-03-28 01:30 UTC, bjk7119 commented on src/fosslight_android/_write_excel.py
> +    header_row.extend(HIDDEN_HEADER)
수정하였습니다.

2024-04-02 23:26 UTC, soimkim commented on src/fosslight_android/_common.py
> +                excel_item.extend(['', '', '', '', '', comment, need_check, self.tlsh, self.checksum])
134, 137 라인에도 출력되어야하는 것으로 보입니다. 
확인 부탁드립니다.

2024-04-03 01:24 UTC, bjk7119 commented on src/fosslight_android/_common.py
> +                excel_item.extend(['', '', '', '', '', comment, need_check, self.tlsh, self.checksum])
134는 적용되어 있고
137에는 추가하였습니다.

2024-04-03 04:08 UTC, merged